# Generated by Django 3.1.7 on 2021-03-04 16:24

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210304_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file_name',
            field=models.ImageField(upload_to='dashboard', validators=[dashboard.validators.image_validate_file_extension]),
        ),
    ]
